[phases.setup]
language = "python"
packages = ["python312"]  # Версия Python, если требуется

[phases.build]
commands = ["pip install -r requirements.txt"]

[phases.start]
commands = ["python my_teleram_bot.py"]

